export const products = [
  {
    id: 'instagenius-ai',
    name: 'InstaGenius AI',
    tagline: 'AI-powered Instagram growth. Create, schedule, and analyze—all in one place.',
    description:
      'Connect your Instagram, generate captions and visuals with AI, schedule posts, and track performance. Built for creators and brands.',
    longDescription: `InstaGenius AI is an Instagram management platform that helps you create, schedule, and analyze—all in one place. Connect multiple accounts, create content with AI-generated captions and images, schedule posts at optimal times, and view analytics from one dashboard. Plans from Free to Enterprise with flexible credits and features.`,
    href: 'https://instagenius.techshekhada.com/',
    cta: 'Try InstaGenius AI',
    badge: 'Flagship',
    features: [
      'AI captions, images & hashtags',
      'Multi-account Instagram management',
      'Smart scheduling & optimal post times',
      'Content library & brand kit',
      'Analytics & insights (7–365 days by plan)',
      'Strategy Hub & Remix Station',
      'Free, Growth, Pro & Enterprise plans',
    ],
  },
  {
    id: 'selleros',
    name: 'SellerOS',
    tagline: 'Smart PDF Sort – Meesho, Snapdeal & Amazon order sorting. Extract SKU, sort order PDFs in seconds.',
    description:
      'Sort order PDFs for Meesho, Snapdeal and Amazon in seconds. Credit-based, secure, built for Indian sellers. Start with free credits.',
    longDescription: `SellerOS by Tech Shekhada does SKU extraction and PDF sorting for Meesho, Snapdeal and Amazon order PDFs. Upload PDFs, get sorted output; optional CSV/Excel for origin labels. Manage SKU inventory, export to Excel, and save time—no manual copy-paste. Credit-based, secure; free credits to start. Access at selleros.techshekhada.com.`,
    href: 'https://selleros.techshekhada.com',
    cta: 'Open SellerOS',
    ctaSubtitle: 'Sign in at selleros.techshekhada.com to sort order PDFs and manage SKU inventory.',
    logoPath: '/selleros-icon.svg',
    fullLogoPath: '/selleros-logo.svg',
    fullLogoPathDark: '/selleros-logo-dark.svg',
    badge: null,
    features: [
      'Meesho Sort – upload PDFs, sorted output; optional CSV/Excel for origin labels',
      'Snapdeal Sort – dedicated flow; extract SKU and quantity; sorted output',
      'Amazon Sort – 2–3 pages per order; extract SKU & quantity; sort by qty then multi-SKU',
      'SKU extraction from order/invoice pages',
      'SKU Inventory – filters, date range, Excel export',
      'Excel/CSV from PDF when needed',
      'One-click sorting for Meesho, Snapdeal, Amazon; no manual copy-paste',
      'Secure, credit-based; free trial, no card required; refer & earn credits',
      'Simple pricing – credit packs, pay per use',
    ],
  },
];
